import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Sesi from "../../public/Sesi.png";
import Link from "next/link";

// NICOLE ESTA FAZENDO ESSA PÁGINA

export default function Perfil() {
  return (
    <div>
      <Head>
        <title>Perfil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <Link href="/" locale="Perfil">
            <Image
              width="112"
              height="35"
              className=" mt-5 mb-5 ml-11"
              src={Sesi}
              alt="Logo do Senai"
            />
          </Link>
          <p>John Doe</p>
        </div>
      </main>
    </div>
  );
}
