import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Sesi from "../../public/Sesi.png";
import Senha from "../../public/senha.png"

export default function Cadastro() {
  return (
    <div className="bodyequivalent">
      <Head>
        <title>Cadastro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="MainCadastro">
        <Link href="/" locale="Cadastro">
          <Image
            width="112"
            height="35"
            className=" mt-8 mb-5 ml-11"
            src={Sesi}
            alt="Logo do Senai"
          />
        </Link>
        <div id="elementosesquerda"> {/*div da esquerda, informações*/}
          <div id="bemvindo">
            <h1 className="bemvindo">Bem-vindo novamente!</h1>
            <h1>Olá, digite as suas informações.</h1>
          </div>
          <div className="inputs">
            <h1 className="cpftxt">CPF</h1>
            <input type="text" placeholder="000.000.000-00"></input>
            <h1 className="senhatxt">Senha</h1>
            <div id="password">
              <input type="text" placeholder="Password"></input>
              <button><Image src={Senha} /></button>
            </div>
          </div>
          <Link
            id="botao"
            href="/UsuarioHome"
            locale="Cadastro"
            className="b1 bg-sky-600 text-white md:text-base text-sm py-4 px-5"
          >
            Entrar
          </Link>
          <div id="loginlog">
            <h1>Não possui uma conta?</h1>
            <Link
              className="loginlink"
              href="../Login/"
            ><h1>Inscreva-se</h1></Link>
          </div>
        </div>
      </main >
    </div >
  );
}
