import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Sesi from "../../assets/Sesi.png";

import { useState } from "react";
import auth from "../../services/auth.js";

export default function Login() {
  const [cpf, setCpf] = useState("");
  const [senha, setSenha] = useState("");

  const cpfMask = (value) => {
    return value
      .replace(/\D/g, "") // substitui qualquer caracter que nao seja numero por nada
      .replace(/(\d{3})(\d)/, "$1.$2") // captura 2 grupos de numero o primeiro de 3 e o segundo de 1, apos capturar o primeiro grupo ele adiciona um ponto antes do segundo grupo de numero
      .replace(/(\d{3})(\d)/, "$1.$2")
      .replace(/(\d{3})(\d{1,2})/, "$1-$2")
      .replace(/(-\d{2})\d+?$/, "$1"); // captura 2 numeros seguidos de um traço e não deixa ser digitado mais nada
  };

  return (
    <div className="bodyequivalentlog">
       <Head>
        <title>Academia Sesi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../sesiIcon.png" />
      </Head>

      <main className="MainCadastro">
        <div className="mt-5 mb-5 ml-11">
          <Link href="/" locale="home">
            <Image width="112" height="35" src={Sesi} alt="Logo do Senai" />
          </Link>
        </div>
        <div id="elementosesquerdalog">
          {" "}
          {/*div da esquerda, informações*/}
          <div id="bemvindo">
            <h1 className="bemvindo">Bem-vindo novamente!</h1>
            <h1>Olá, digite as suas informações.</h1>
          </div>
          <div className="inputs">
            <h1 className="cpftxt">CPF</h1>
            <input
              type="text"
              placeholder="000.000.000-00"
              value={cpf}
              maxLength={14}
              onChange={(e) => setCpf(cpfMask(e.target.value))}
            ></input>
            <h1 className="senhatxt">Senha</h1>
            <div id="password">
              <input
                type="password"
                placeholder="Password"
                value={senha}
                onChange={(e) => setSenha(e.target.value)}
              ></input>
            </div>
          </div>
          <button
            id="botaolog"
            className="b1 bg-sky-600 text-white md:text-base text-sm py-4 px-5"
            onClick={() =>
              (window.location.pathname = auth.entrarConta(cpf, senha))
            }
          >
            Entrar
          </button>
          <div id="loginlog">
            <h1>Não possui uma conta?</h1>
            <Link className="loginlink" href="../../cadastro">
              <h1>Inscreva-se</h1>
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
}
