import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Sesi from "../../assets/Sesi.png";
import Link from "next/link";
import construção from "../../assets/usuarioHome.png";

// NICOLE ESTA FAZENDO ESSA PÁGINA

export default function UsuarioHome() {
  return (
    <div>
      <Head>
        <title>Academia Sesi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../sesiIcon.png" />
      </Head>

      <main>
        <div className="inline-block mt-5 mb-5 ml-11">
          <Link href="/" locale="homeusuario">
            <Image width="112" height="35" src={Sesi} alt="Logo do Senai" />
          </Link>
        </div>
        <div className="mt-16">
          <div className="flex">
            <Image
              width="500"
              src={construção}
              alt="Desenho de construção"
              className="mx-auto"
            />
          </div>
          <div className="mt-6 text-center">
            <p>Página ainda em construção!</p>
            <div className="mt-6">
              <Link
                href="/profile"
                locale="usuarioHome"
                className="b1 bg-sky-600 text-white md:text-base text-sm py-2 px-16 rounded-lg"
              >
                Acessar perfil
              </Link>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
