import Head from "next/head";
import Image from "next/image";
import Sesi from "../public/Sesi.png";
import Link from "next/link";
import Retangulo from "../public/Retangulo.svg";

// NICOLE ESTA FAZENDO ESSA PÁGINA

export default function Home() {
  return (
    <div>
      <Head>
        <title>Academia Sesi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="wppHome">
        <nav>
          <Image
            width="112"
            height="35"
            className="logo"
            src={Sesi}
            alt="Logo do Senai"
          />
          <lu>
            <li>
              <Link href="/" locale="home">
                Início
              </Link>
            </li>

            <li>
              <Link
                href="https://sesisc.org.br/sobre-sesi"
                locale="home"
                target="_blank"
              >
                Conheça mais
              </Link>
            </li>

            <li>
              <Link
                href="https://transparencia.sesisc.org.br/fale-conosco?entidade=sesi"
                locale="home"
                target="_blank"
              >
                Entre em contato
              </Link>
            </li>
          </lu>
        </nav>
        <Image
            width="509"
            height="915"
            className="retangulo"
            src={Retangulo}
            alt="Logo do Senai"
          />
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
