import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Sesi from "../../public/Sesi.png";

export default function Cadastro() {
  return (
    <div>
      <Head>
        <title>Cadastro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Link href="/" locale="Cadastro">
          <Image
            width="112"
            height="35"
            className=" mt-5 mb-5 ml-11"
            src={Sesi}
            alt="Logo do Senai"
          />
        </Link>
        <Link
          href="/UsuarioHome"
          locale="Cadastro"
          className=" ml-5 border-solid border-2 border-sky-600 md:text-base text-sm text-sky-600 py-3 px-9 rounded-3xl"
        >
          Cadastrar
        </Link>
      </main>
    </div>
  );
}
