import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Sesi from "../../public/Sesi.png";
import Link from "next/link";

// NICOLE ESTA FAZENDO ESSA PÁGINA

export default function UsuarioHome() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/sesiIcon" />
      </Head>

      <main>
        <div>
        <Link href="/" locale="UsuarioHome">
            <Image
              width="112"
              height="35"
              className=" mt-5 mb-5 ml-11"
              src={Sesi}
              alt="Logo do Senai"
            />
          </Link>
          <p>Página ainda em construção!</p>
          <Link
            href="/Perfil"
            locale="UsuarioHome"
            className=" ml-5 border-solid border-2 border-sky-600 md:text-base text-sm text-sky-600 py-3 px-9 rounded-3xl"
          >
            Acessar perfil
          </Link>
        </div>
      </main>
    </div>
  );
}
